### PR TITLE
made it better than limas

### PR DESCRIPTION
**Pull request by Misly16**

### CODE REVIEW

**Review by CorruptedPixl — APPROVED** [review]
Should be good

**Review by gtsatsis — CHANGES_REQUESTED** [review]
In my opinion, there should be more than a `.bannable` check, as a person that is lower in the hierarchy of the server, with permissions to the bot, say a Moderator, could ban and Administrator, while normally discord would forbid that due to the hierarchy of the roles.

**Comment by CorruptedPixl** [comment]
Fair point, as stated previously I'll check this myself before merging when development resumes.

**Comment by Misly16** [comment]
The bot can be placed under the admin/mod role

**Comment by lima0** [comment]
"made it good" 
image

**Comment by lima0** [comment]
also the ` if (!message.member.hasPermission("BAN_MEMBERS")) {message.reply('nah bro you\'re not worthy of the hammer')}` line, add `return` before the message.reply to exit the function

**Comment by Misly16** [comment]
Shut the fuck up , you should if fixed that

**Comment by lima0** [comment]
https://help.github.com/articles/github-community-guidelines
^ github community guidelines, check them out, also chill dude its just some code

**Comment by Misly16** [comment]
> https://help.github.com/articles/github-community-guidelines
> ^ github community guidelines, check them out, also chill dude its just some code

I apologise and you did write the code https://user-images.githubusercontent.com/47898885/82139078-b53b5d80-9825-11ea-8a69-d4265e998b04.png

**Comment by Misly16** [comment]
I will close because pixl not currently make bot

**Comment by gtsatsis** [comment]
@lima0 lol fuck the guidelines, Mauro (see: LKML top 50 to understand)

**Pull request closed without merging**
